### ISSUE TITLE
App crashing when trying to download big Smart Controller firmware

### ISSUE THREAD

**Issue by ddzobov** [cs2000/DankDroneDownloader#18] opened 2021-07-23 23:02 UTC
For example, 01.01.0040 - crashing

**Comment by cs2000** [comment] 2021-07-24 09:38
Bug Confirmed, it looks to be an issue with the component that deals with temporarily storing the file while its contents are streamed before it prompts you to save it.

Im looking for the specific issue and will release a new version, along with (finally) the ability to filter by brand natively in the app when i find the root cause.

**Comment by cs2000** [comment] 2021-07-31 09:43
Issue now fixed with build 7638.2078, thanks for the report!

**Closed by cs2000** 2021-07-31 09:43 UTC
Labels: bug
